M48
; DRILL file {KiCad 9.0.2} date 2026-04-05T15:38:38+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-05T15:38:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X111.307Y-48.75
X117.087Y-48.75
T2
X96.33Y-47.78
X96.33Y-96.75
X167.8Y-47.78
X167.8Y-96.75
M30
